version: '2.4'

services:
  cli:
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_VERSION}
    restart: 'no'
    tty: true # Colorize logs
    env_file:
      - ./.env
    command:
      - bash
      - -c
      - ':
        && set -x
        && echo Installing node modules
        && yarn
        && echo Container is READY
        && sleep infinity
        '
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - node_home:/home/node

  worker:
    command:
      - bash
      - -c
      - ':
        && set -x
        && echo Installing node modules
        && yarn
        && yarn nodemon -V -w ./src ./src/cli.js worker check
        '
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - node_home:/home/node

  server:
    command:
      - bash
      - -c
      - ':
        && set -x
        && echo Installing node modules
        && yarn
        && yarn nodemon -V -w ./src ./src/cli.js worker check
        '
    environment:
      NODE_ENV: development
      # DEBUG: http,express:*
    volumes:
      - ./:/app
      - node_home:/home/node

volumes:
  node_home:
