version: '2.4'

services:
  worker:
    depends_on:
      - redis
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_VERSION}
    stop_grace_period: 2m
    restart: always
    tty: true # Colorize logs
    env_file:
      - ./.env
    command:
      - ./src/cli.js
      - worker
      - check

  server:
    depends_on:
      - redis
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_VERSION}
    restart: always
    tty: true # Colorize logs
    env_file:
      - ./.env
    command:
      - ./src/cli.js
      - server
      - start
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:purr.traefik.lcl'

  storage:
    image: nginx:alpine
    restart: always
    tty: true # Colorize logs
    env_file:
      - ./.env
    volumes:
      # TODO: fix permission if ./storage not exists
      - ./storage:/usr/share/nginx/html/storage:ro
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:purr.traefik.lcl;PathPrefix:/storage'

  redis:
    image: redis
    restart: always
